import {
  pgTable,
  text,
  uuid,
  timestamp,
  integer,
  boolean,
  real,
  pgEnum,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Enums ───────────────────────────────────────────────────────────

export const promptCategoryEnum = pgEnum("prompt_category", [
  "general",
  "comparison",
  "recommendation",
  "pricing",
  "review",
  "alternative",
  "how_to",
]);

export const checkStatusEnum = pgEnum("check_status", [
  "pending",
  "running",
  "completed",
  "failed",
]);

export const sentimentLabelEnum = pgEnum("sentiment_label", [
  "positive",
  "neutral",
  "negative",
]);

export const hallucinationSeverityEnum = pgEnum("hallucination_severity", [
  "low",
  "medium",
  "high",
  "critical",
]);

export const factCategoryEnum = pgEnum("fact_category", [
  "pricing",
  "feature",
  "founding",
  "location",
  "product",
  "metric",
  "other",
]);

// ─── Users ───────────────────────────────────────────────────────────

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  name: text("name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// ─── API Keys ────────────────────────────────────────────────────────

export const apiKeys = pgTable(
  "api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    keyHash: text("key_hash").notNull(),
    keyPrefix: text("key_prefix").notNull(), // e.g. "xel_sk_abc1"
    label: text("label"),
    isActive: boolean("is_active").default(true).notNull(),
    lastUsedAt: timestamp("last_used_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("api_keys_user_id_idx").on(t.userId)]
);

// ─── Webhooks ────────────────────────────────────────────────────────

export const webhooks = pgTable("webhooks", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  url: text("url").notNull(),
  events: jsonb("events").$type<string[]>().notNull(),
  secret: text("secret").notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Brands ──────────────────────────────────────────────────────────

export const brands = pgTable(
  "brands",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    domain: text("domain"),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("brands_user_id_idx").on(t.userId)]
);

// ─── Brand Facts ─────────────────────────────────────────────────────

export const brandFacts = pgTable(
  "brand_facts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    category: factCategoryEnum("category").notNull(),
    key: text("key").notNull(),
    value: text("value").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("brand_facts_brand_id_idx").on(t.brandId)]
);

// ─── Competitors ─────────────────────────────────────────────────────

export const competitors = pgTable(
  "competitors",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    domain: text("domain"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("competitors_brand_id_idx").on(t.brandId)]
);

// ─── Prompts ─────────────────────────────────────────────────────────

export const prompts = pgTable(
  "prompts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    text: text("text").notNull(),
    category: promptCategoryEnum("category").notNull(),
    isAutoGenerated: boolean("is_auto_generated").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("prompts_brand_id_idx").on(t.brandId)]
);

// ─── Checks ──────────────────────────────────────────────────────────

export const checks = pgTable(
  "checks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    promptId: uuid("prompt_id")
      .notNull()
      .references(() => prompts.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    status: checkStatusEnum("status").default("pending").notNull(),
    responseText: text("response_text"),
    latencyMs: integer("latency_ms"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    completedAt: timestamp("completed_at"),
  },
  (t) => [
    index("checks_brand_id_idx").on(t.brandId),
    index("checks_status_idx").on(t.status),
  ]
);

// ─── Mentions ────────────────────────────────────────────────────────

export const mentions = pgTable(
  "mentions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    checkId: uuid("check_id")
      .notNull()
      .references(() => checks.id, { onDelete: "cascade" }),
    brandName: text("brand_name").notNull(),
    isMentioned: boolean("is_mentioned").notNull(),
    position: integer("position"), // 1-indexed rank in the response
    sentimentScore: real("sentiment_score"), // -1 to 1
    sentimentLabel: sentimentLabelEnum("sentiment_label"),
    context: text("context"), // surrounding text excerpt
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("mentions_check_id_idx").on(t.checkId)]
);

// ─── Citations ───────────────────────────────────────────────────────

export const citations = pgTable(
  "citations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    checkId: uuid("check_id")
      .notNull()
      .references(() => checks.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    domain: text("domain").notNull(),
    isBrandUrl: boolean("is_brand_url").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("citations_check_id_idx").on(t.checkId)]
);

// ─── Hallucinations ─────────────────────────────────────────────────

export const hallucinations = pgTable(
  "hallucinations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    checkId: uuid("check_id")
      .notNull()
      .references(() => checks.id, { onDelete: "cascade" }),
    factId: uuid("fact_id").references(() => brandFacts.id, {
      onDelete: "set null",
    }),
    claim: text("claim").notNull(),
    expectedValue: text("expected_value"),
    actualValue: text("actual_value"),
    severity: hallucinationSeverityEnum("severity").notNull(),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("hallucinations_check_id_idx").on(t.checkId)]
);

// ─── Relations ───────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many }) => ({
  brands: many(brands),
  apiKeys: many(apiKeys),
  webhooks: many(webhooks),
}));

export const brandsRelations = relations(brands, ({ one, many }) => ({
  user: one(users, { fields: [brands.userId], references: [users.id] }),
  facts: many(brandFacts),
  competitors: many(competitors),
  prompts: many(prompts),
  checks: many(checks),
}));

export const brandFactsRelations = relations(brandFacts, ({ one }) => ({
  brand: one(brands, { fields: [brandFacts.brandId], references: [brands.id] }),
}));

export const competitorsRelations = relations(competitors, ({ one }) => ({
  brand: one(brands, {
    fields: [competitors.brandId],
    references: [brands.id],
  }),
}));

export const promptsRelations = relations(prompts, ({ one, many }) => ({
  brand: one(brands, { fields: [prompts.brandId], references: [brands.id] }),
  checks: many(checks),
}));

export const checksRelations = relations(checks, ({ one, many }) => ({
  brand: one(brands, { fields: [checks.brandId], references: [brands.id] }),
  prompt: one(prompts, { fields: [checks.promptId], references: [prompts.id] }),
  mentions: many(mentions),
  citations: many(citations),
  hallucinations: many(hallucinations),
}));

export const mentionsRelations = relations(mentions, ({ one }) => ({
  check: one(checks, { fields: [mentions.checkId], references: [checks.id] }),
}));

export const citationsRelations = relations(citations, ({ one }) => ({
  check: one(checks, { fields: [citations.checkId], references: [checks.id] }),
}));

export const hallucinationsRelations = relations(
  hallucinations,
  ({ one }) => ({
    check: one(checks, {
      fields: [hallucinations.checkId],
      references: [checks.id],
    }),
    fact: one(brandFacts, {
      fields: [hallucinations.factId],
      references: [brandFacts.id],
    }),
  })
);

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  user: one(users, { fields: [apiKeys.userId], references: [users.id] }),
}));

export const webhooksRelations = relations(webhooks, ({ one }) => ({
  user: one(users, { fields: [webhooks.userId], references: [users.id] }),
}));
