import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import { eq, and } from "drizzle-orm";
import {
  brands,
  brandFacts,
  competitors as competitorsTable,
  prompts,
  checks,
  mentions,
  citations,
  hallucinations,
} from "@xelin/db";
import { getDb } from "../db.js";
import type { AuthEnv } from "../middleware/auth.js";
import {
  XelinEngine,
  type ProviderConfig,
  type BrandFact,
  type CompetitorInfo,
} from "@xelin/core";

const createCheckSchema = z.object({
  brandId: z.string().uuid(),
  providers: z
    .array(
      z.object({
        provider: z.enum([
          "openai",
          "anthropic",
          "google",
          "perplexity",
          "bedrock",
        ]),
        model: z.string(),
      })
    )
    .min(1),
  prompts: z
    .array(
      z.object({
        text: z.string(),
        category: z.enum([
          "general",
          "comparison",
          "recommendation",
          "pricing",
          "review",
          "alternative",
          "how_to",
        ]),
      })
    )
    .optional(),
  concurrency: z.number().min(1).max(10).default(3),
});

export const checkRoutes = new Hono<AuthEnv>();

// Run a check synchronously
checkRoutes.post("/", zValidator("json", createCheckSchema), async (c) => {
  const data = c.req.valid("json");
  const userId = c.get("userId");
  const db = getDb();

  // Fetch brand with facts and competitors
  const brand = await db.query.brands.findFirst({
    where: and(eq(brands.id, data.brandId), eq(brands.userId, userId)),
    with: { facts: true, competitors: true },
  });

  if (!brand) return c.json({ error: "Brand not found" }, 404);

  // Build engine
  const engine = new XelinEngine({
    providers: data.providers as ProviderConfig[],
    concurrency: data.concurrency,
    prompts: data.prompts,
  });

  // Run the check
  const report = await engine.runCheck({
    name: brand.name,
    domain: brand.domain ?? undefined,
    description: brand.description ?? undefined,
    facts: brand.facts.map(
      (f) =>
        ({
          category: f.category,
          key: f.key,
          value: f.value,
        }) as BrandFact
    ),
    competitors: brand.competitors.map(
      (comp) =>
        ({
          name: comp.name,
          domain: comp.domain ?? undefined,
        }) as CompetitorInfo
    ),
  });

  // Persist results to database
  for (const checkResult of report.checks) {
    // Create prompt record
    const [promptRecord] = await db
      .insert(prompts)
      .values({
        brandId: brand.id,
        text: checkResult.prompt,
        category: checkResult.promptCategory as any,
        isAutoGenerated: !data.prompts,
      })
      .returning();

    // Create check record
    const [checkRecord] = await db
      .insert(checks)
      .values({
        brandId: brand.id,
        promptId: promptRecord.id,
        provider: checkResult.provider,
        model: checkResult.model,
        status: "completed",
        responseText: checkResult.responseText,
        latencyMs: checkResult.latencyMs,
        completedAt: new Date(),
      })
      .returning();

    // Insert mentions
    if (checkResult.mentions.length > 0) {
      await db.insert(mentions).values(
        checkResult.mentions.map((m) => ({
          checkId: checkRecord.id,
          brandName: m.brandName,
          isMentioned: m.isMentioned,
          position: m.position,
          sentimentScore: m.sentimentScore,
          sentimentLabel: m.sentimentLabel as any,
          context: m.context,
        }))
      );
    }

    // Insert citations
    if (checkResult.citations.length > 0) {
      await db.insert(citations).values(
        checkResult.citations.map((cit) => ({
          checkId: checkRecord.id,
          url: cit.url,
          domain: cit.domain,
          isBrandUrl: cit.isBrandUrl,
        }))
      );
    }

    // Insert hallucinations
    if (checkResult.hallucinations.length > 0) {
      await db.insert(hallucinations).values(
        checkResult.hallucinations.map((h) => ({
          checkId: checkRecord.id,
          claim: h.claim,
          expectedValue: h.expectedValue,
          actualValue: h.actualValue,
          severity: h.severity as any,
          description: h.description,
        }))
      );
    }
  }

  return c.json(
    {
      brandId: brand.id,
      visibility: report.visibility,
      sentiment: report.sentiment,
      shareOfVoice: report.shareOfVoice,
      accuracy: report.accuracy,
      hallucinationRate: report.hallucinationRate,
      hallucinations: report.hallucinations,
      totalChecks: report.totalChecks,
    },
    200
  );
});

// Get check results for a brand
checkRoutes.get("/:brandId", async (c) => {
  const brandId = c.req.param("brandId");
  const userId = c.get("userId");
  const db = getDb();

  // Verify ownership
  const brand = await db.query.brands.findFirst({
    where: and(eq(brands.id, brandId), eq(brands.userId, userId)),
  });
  if (!brand) return c.json({ error: "Brand not found" }, 404);

  const results = await db.query.checks.findMany({
    where: eq(checks.brandId, brandId),
    with: {
      prompt: true,
      mentions: true,
      citations: true,
      hallucinations: true,
    },
    orderBy: (checks, { desc }) => [desc(checks.createdAt)],
    limit: 50,
  });

  return c.json(results);
});
